// Auto-generated by AppKit - DO NOT EDIT
// Generated by 'npx @databricks/appkit generate-types' or Vite plugin during build
import "@databricks/appkit-ui/react";
import type { SQLTypeMarker, SQLStringMarker, SQLNumberMarker, SQLBooleanMarker, SQLBinaryMarker, SQLDateMarker, SQLTimestampMarker } from "@databricks/appkit-ui/js";

declare module "@databricks/appkit-ui/react" {
  interface QueryRegistry {
    acompanhamento: {
        name: "acompanhamento";
        parameters: Record<string, never>;
        result: Array<{
          /** Nome do vendedor responsável pela ligação, de gold.dim_vendedor. */
          vendedor: string;
          /** @sqlType BIGINT */
          na_fila: number;
          /** @sqlType BIGINT */
          trabalhados: number;
          /** @sqlType BIGINT */
          vendeu: number;
          /** @sqlType BIGINT */
          vai_pensar: number;
          /** @sqlType BIGINT */
          sem_interesse: number;
          /** @sqlType BIGINT */
          nao_atendeu: number;
        }>;
      };
    fila: {
        name: "fila";
        parameters: {
          /** STRING - use sql.string() */
          vendedor: SQLStringMarker;
        };
        result: Array<{
          /** Nome do vendedor responsável pela ligação, de gold.dim_vendedor. */
          vendedor: string;
          /** Posição do cliente na fila DESTE vendedor, por score decrescente (1 = prioridade máxima). Não é a posição na fila geral de 200. */
          ordem: number;
          /** Cliente selecionado para contato esta semana. */
          cliente_id: number;
          /** Razão social do cliente, de gold.dim_cliente. */
          razao_social: string;
          /** Cidade do cliente, de gold.dim_cliente. */
          cidade: string;
          /** UF do cliente, de gold.dim_cliente. */
          uf: string;
          /** Ticket médio histórico do cliente, de gold.features_cliente. */
          ticket_medio: number;
          /** Score de propensão de compra em 7 dias (0 a 1), de gold.score_propensao. */
          score: number;
          /** Faixa do score (Fria/Morna/Quente/Muito quente), de gold.score_propensao. */
          faixa: string;
          /** Explicação em português de por que este cliente está na fila, com os números reais dele. Nunca nulo — é o que o vendedor lê antes de ligar, e o que o Genie usa para responder "por que" sem inventar. */
          motivo: string;
          /** SKU mais comprado historicamente na marca preferida do cliente, entre os que ele não comprou nos últimos 90 dias, com o saldo do snapshot mais recente de estoque. Pode ser NULL (cliente sem histórico de marca com SKU recorrente). */
          sugestao: string;
          /** @sqlType DATE */
          referencia_fila: string;
          /** Resultado da ligação. Único vocabulário válido: vendeu | vai_pensar | sem_interesse | nao_atendeu. */
          status_retorno: string;
          /** Texto livre do vendedor sobre a ligação. Pode ser NULL — nem toda ligação gera comentário. */
          comentario_retorno: string;
        }>;
      };
    kpis_semana: {
        name: "kpis_semana";
        parameters: Record<string, never>;
        result: Array<{
          /** @sqlType BIGINT */
          contatos: number;
          /** @sqlType BIGINT */
          vendedores: number;
          /** @sqlType DOUBLE */
          receita_esperada: number;
          /** @sqlType TIMESTAMP */
          referencia_fila: string;
          /** @sqlType BIGINT */
          acertos_top200: number;
          /** @sqlType DOUBLE */
          lift_top200: number;
          /** @sqlType DOUBLE */
          taxa_base: number;
          /** @sqlType BIGINT */
          ligacoes_registradas: number;
          /** @sqlType BIGINT */
          viraram_pedido: number;
        }>;
      };
    vendedores: {
        name: "vendedores";
        parameters: Record<string, never>;
        result: Array<{
          /** Nome do vendedor responsável pela ligação, de gold.dim_vendedor. */
          vendedor: string;
          /** @sqlType BIGINT */
          contatos: number;
        }>;
      };
  }
}
